package dev.iadev.assembler;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

/**
 * Consolidates multiple source files into merged outputs
 * with generated headers and separators.
 *
 * <p>Used by assemblers to merge framework-specific rules
 * into consolidated files grouped by category (core, data,
 * operations).</p>
 *
 * <p>Example usage:
 * <pre>{@code
 * Consolidator.consolidateFiles(
 *     outputPath, List.of(file1, file2));
 * Consolidator.consolidateFrameworkRules(
 *     "quarkus", rulesDir, sourceDir);
 * }</pre>
 * </p>
 */
public final class Consolidator {

    /** Header prepended to every consolidated output. */
    public static final String GENERATED_HEADER =
            "<!-- Generated by ia-dev-env"
                    + " -- DO NOT EDIT DIRECTLY -->";

    /** Filename patterns for core framework extensions. */
    public static final List<String> CORE_PATTERNS =
            List.of("-cdi", "-di", "-config", "-web",
                    "-resteasy", "-middleware", "-resilience");

    /** Filename patterns for data-layer extensions. */
    public static final List<String> DATA_PATTERNS =
            List.of("-panache", "-jpa", "-prisma",
                    "-sqlalchemy", "-exposed", "-ef",
                    "-orm", "-database");

    /** Filename patterns for operations extensions. */
    public static final List<String> OPS_PATTERNS =
            List.of("-testing", "-observability",
                    "-native-build", "-infrastructure");

    private Consolidator() {
        // Utility class — no instantiation
    }

    /**
     * Merges multiple source files into a single output.
     *
     * <p>Adds a generated header and {@code ---} separators
     * between sections. Creates parent directories if needed.
     * Skips files that do not exist.</p>
     *
     * @param outputPath  the merged output file path
     * @param sourcePaths the list of source file paths
     */
    public static void consolidateFiles(
            Path outputPath,
            List<Path> sourcePaths) {
        List<Path> existing = sourcePaths.stream()
                .filter(p -> Files.exists(p)
                        && Files.isRegularFile(p))
                .toList();

        if (existing.isEmpty()) {
            return;
        }

        try {
            Files.createDirectories(outputPath.getParent());

            List<String> lines = new ArrayList<>();
            lines.add(GENERATED_HEADER);
            lines.add("");

            for (Path src : existing) {
                lines.add("");
                lines.add("---");
                lines.add("");
                lines.add(Files.readString(
                        src, StandardCharsets.UTF_8));
                lines.add("");
            }

            Files.writeString(outputPath,
                    String.join("\n", lines),
                    StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException(
                    "Failed to consolidate files to: "
                            + outputPath, e);
        }
    }

    /**
     * Groups framework files into 3 consolidated outputs
     * (core, data, ops).
     *
     * @param framework the framework name (sanitized)
     * @param rulesDir  the directory for consolidated output
     * @param sourceDir the directory containing source files
     * @return list of generated file paths (only non-empty
     *         groups)
     */
    public static List<String> consolidateFrameworkRules(
            String framework,
            Path rulesDir,
            Path sourceDir) {
        if (!Files.exists(sourceDir)
                || !Files.isDirectory(sourceDir)) {
            return List.of();
        }

        String safeFramework =
                sanitizeFilenameSegment(framework);

        List<Path> allFiles;
        try (Stream<Path> stream = Files.list(sourceDir)) {
            allFiles = stream
                    .filter(f -> f.toString().endsWith(".md"))
                    .sorted()
                    .toList();
        } catch (IOException e) {
            throw new UncheckedIOException(
                    "Failed to list directory: "
                            + sourceDir, e);
        }

        List<Path> core = new ArrayList<>();
        List<Path> data = new ArrayList<>();
        List<Path> ops = new ArrayList<>();

        for (Path file : allFiles) {
            String name = file.getFileName().toString();
            if (matchesAny(name, CORE_PATTERNS)) {
                core.add(file);
            } else if (matchesAny(name, DATA_PATTERNS)) {
                data.add(file);
            } else if (matchesAny(name, OPS_PATTERNS)) {
                ops.add(file);
            }
        }

        List<String> generated = new ArrayList<>();
        consolidateGroup(
                rulesDir, safeFramework,
                "30", "core", core, generated);
        consolidateGroup(
                rulesDir, safeFramework,
                "31", "data", data, generated);
        consolidateGroup(
                rulesDir, safeFramework,
                "32", "operations", ops, generated);

        return generated;
    }

    /**
     * Strips path separators and parent-directory sequences
     * from a filename segment.
     *
     * <p>Prevents path traversal when user-supplied values
     * (e.g., framework name) are interpolated into output
     * filenames.</p>
     *
     * @param segment the raw filename segment
     * @return the sanitized segment
     */
    public static String sanitizeFilenameSegment(
            String segment) {
        return segment
                .replace("/", "")
                .replace("\\", "")
                .replace("..", "");
    }

    private static void consolidateGroup(
            Path rulesDir,
            String framework,
            String prefix,
            String label,
            List<Path> files,
            List<String> generated) {
        if (files.isEmpty()) {
            return;
        }
        Path output = rulesDir.resolve(
                prefix + "-" + framework + "-" + label + ".md");
        consolidateFiles(output, files);
        generated.add(output.toString());
    }

    private static boolean matchesAny(
            String filename, List<String> patterns) {
        return patterns.stream()
                .anyMatch(filename::contains);
    }
}
