package dev.iadev.assembler;

import dev.iadev.model.ProjectFoundation;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Builds the generation summary table and settings section
 * for README.md.
 *
 * <p>Generates component counts for all artifact types
 * across .claude/, .github/, .codex/, and .agents/
 * directories. Also provides the static settings
 * documentation section.</p>
 *
 * @see ReadmeTables
 * @see ReadmeUtils
 */
public final class SummaryTableBuilder {

    SummaryTableBuilder() {
        // package-private constructor
    }

    /**
     * Builds the generation summary table with component
     * counts.
     *
     * @param outputDir the .claude/ output directory
     * @return formatted generation summary
     */
    String buildGenerationSummary(Path outputDir) {
        Path githubDir = resolveGithubDir(outputDir);
        Object[][] rows =
                buildSummaryRows(outputDir, githubDir);
        List<String> lines = new ArrayList<>();
        lines.add("| Component | Count |");
        lines.add("|-----------|-------|");
        for (Object[] row : rows) {
            lines.add("| %s | %s |"
                    .formatted(row[0], row[1]));
        }
        lines.add("");
        String ver = ProjectFoundation.DEFAULT.version();
        lines.add("Generated by `ia-dev-env v%s`."
                .formatted(ver));
        return String.join("\n", lines);
    }

    /**
     * Builds static settings section content.
     *
     * @return formatted settings section
     */
    String buildSettingsSection() {
        return "### settings.json\n"
                + "\n"
                + "Permissions are configured in"
                + " `settings.json`"
                + " under `permissions.allow`.\n"
                + "This controls which Bash commands"
                + " Claude Code"
                + " can run without asking.\n"
                + "\n"
                + "### settings.local.json\n"
                + "\n"
                + "Local overrides (gitignored)."
                + " Use for personal"
                + " preferences or team-specific tools.\n"
                + "\n"
                + "See the files directly for current"
                + " configuration.";
    }

    static Path resolveGithubDir(Path outputDir) {
        return outputDir.getParent().resolve(".github");
    }

    private static Path resolveCodexDir(Path outputDir) {
        return outputDir.getParent().resolve(".codex");
    }

    private static Path resolveAgentsDir(Path outputDir) {
        return outputDir.getParent().resolve(".agents");
    }

    private static Object[][] buildSummaryRows(
            Path outputDir, Path githubDir) {
        int kps = ReadmeUtils
                .countKnowledgePacks(outputDir);
        int ghGlobal = Files.exists(
                githubDir.resolve(
                        "copilot-instructions.md")) ? 1 : 0;
        int ghMcp = Files.exists(
                githubDir.resolve(
                        "copilot-mcp.json")) ? 1 : 0;
        Path codexDir = resolveCodexDir(outputDir);
        int codexCount =
                ReadmeUtils.countCodexFiles(codexDir);
        Path agentsDir = resolveAgentsDir(outputDir);
        int agentsCount =
                ReadmeUtils.countCodexAgentsFiles(agentsDir);
        Path rootDir = outputDir.getParent();
        int agentsMdCount = Files.exists(
                rootDir.resolve("AGENTS.md")) ? 1 : 0;

        return new Object[][]{
                {"Rules (.claude)",
                        ReadmeUtils.countRules(outputDir)},
                {"Skills (.claude)",
                        ReadmeUtils.countSkills(outputDir)
                                - kps},
                {"Knowledge Packs (.claude)", kps},
                {"Agents (.claude)",
                        ReadmeUtils.countAgents(outputDir)},
                {"Hooks (.claude)",
                        ReadmeUtils.countHooks(outputDir)},
                {"Settings (.claude)",
                        ReadmeUtils
                                .countSettings(outputDir)},
                {"Instructions (.github)",
                        ReadmeUtils.countGithubComponent(
                                githubDir, "instructions")
                                + ghGlobal},
                {"Skills (.github)",
                        ReadmeUtils.countGithubSkills(
                                githubDir)},
                {"Agents (.github)",
                        ReadmeUtils.countGithubComponent(
                                githubDir, "agents")},
                {"Prompts (.github)",
                        ReadmeUtils.countGithubComponent(
                                githubDir, "prompts")},
                {"Hooks (.github)",
                        ReadmeUtils.countGithubComponent(
                                githubDir, "hooks")},
                {"MCP (.github)", ghMcp},
                {"AGENTS.md (root)", agentsMdCount},
                {"Codex (.codex)", codexCount},
                {"Skills (.agents)", agentsCount},
        };
    }
}
