package dev.iadev.assembler;

import dev.iadev.domain.model.ProjectFoundation;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Builds the generation summary table and settings section
 * for README.md.
 *
 * <p>Generates component counts for all artifact types
 * across .claude/, .github/, .codex/, and .agents/
 * directories. Also provides the static settings
 * documentation section.</p>
 *
 * @see ReadmeTables
 * @see ReadmeUtils
 */
public final class SummaryTableBuilder {

    SummaryTableBuilder() {
        // package-private constructor
    }

    /**
     * Builds the generation summary table with component
     * counts.
     *
     * @param outputDir the .claude/ output directory
     * @return formatted generation summary
     */
    String buildGenerationSummary(Path outputDir) {
        Path githubDir = resolveGithubDir(outputDir);
        Object[][] rows =
                buildSummaryRows(outputDir, githubDir);
        List<String> lines = new ArrayList<>();
        lines.add("| Component | Count |");
        lines.add("|-----------|-------|");
        for (Object[] row : rows) {
            lines.add("| %s | %s |"
                    .formatted(row[0], row[1]));
        }
        lines.add("");
        String ver = ProjectFoundation.DEFAULT.version();
        lines.add("Generated by `ia-dev-env v%s`."
                .formatted(ver));
        return String.join("\n", lines);
    }

    /**
     * Builds static settings section content.
     *
     * @return formatted settings section
     */
    String buildSettingsSection() {
        return "### settings.json\n"
                + "\n"
                + "Permissions are configured in"
                + " `settings.json`"
                + " under `permissions.allow`.\n"
                + "This controls which Bash commands"
                + " Claude Code"
                + " can run without asking.\n"
                + "\n"
                + "### settings.local.json\n"
                + "\n"
                + "Local overrides (gitignored)."
                + " Use for personal"
                + " preferences or team-specific tools.\n"
                + "\n"
                + "See the files directly for current"
                + " configuration.";
    }

    static Path resolveGithubDir(Path outputDir) {
        return outputDir.getParent().resolve(".github");
    }

    private static Path resolveCodexDir(Path outputDir) {
        return outputDir.getParent().resolve(".codex");
    }

    private static Path resolveAgentsDir(Path outputDir) {
        return outputDir.getParent().resolve(".agents");
    }

    private static Object[][] buildSummaryRows(
            Path outputDir, Path githubDir) {
        Object[][] claudeRows =
                buildClaudeRows(outputDir);
        Object[][] githubRows =
                buildGithubRows(outputDir, githubDir);
        Object[][] extRows =
                buildExtensionRows(outputDir);
        return concatRows(
                claudeRows, githubRows, extRows);
    }

    private static Object[][] buildClaudeRows(
            Path outputDir) {
        int kps = ReadmeUtils
                .countKnowledgePacks(outputDir);
        return new Object[][]{
                {"Rules (.claude)",
                        ReadmeUtils.countRules(outputDir)},
                {"Skills (.claude)",
                        ReadmeUtils.countSkills(outputDir)
                                - kps},
                {"Knowledge Packs (.claude)", kps},
                {"Agents (.claude)",
                        ReadmeUtils.countAgents(outputDir)},
                {"Hooks (.claude)",
                        ReadmeUtils.countHooks(outputDir)},
                {"Settings (.claude)",
                        ReadmeUtils.countSettings(outputDir)},
        };
    }

    private static Object[][] buildGithubRows(
            Path outputDir, Path githubDir) {
        int ghGlobal = existsAsInt(
                githubDir, "copilot-instructions.md");
        int ghMcp = existsAsInt(
                githubDir, "copilot-mcp.json");
        return new Object[][]{
                {"Instructions (.github)",
                        ghComponent(githubDir,
                                "instructions") + ghGlobal},
                {"Skills (.github)",
                        ReadmeUtils.countGithubSkills(
                                githubDir)},
                {"Agents (.github)",
                        ghComponent(githubDir, "agents")},
                {"Prompts (.github)",
                        ghComponent(githubDir, "prompts")},
                {"Hooks (.github)",
                        ghComponent(githubDir, "hooks")},
                {"MCP (.github)", ghMcp},
        };
    }

    private static int existsAsInt(
            Path dir, String filename) {
        return Files.exists(dir.resolve(filename)) ? 1 : 0;
    }

    private static int ghComponent(
            Path githubDir, String name) {
        return ReadmeUtils.countGithubComponent(
                githubDir, name);
    }

    private static Object[][] buildExtensionRows(
            Path outputDir) {
        Path codexDir = resolveCodexDir(outputDir);
        int codexCount =
                ReadmeUtils.countCodexFiles(codexDir);
        Path agentsDir = resolveAgentsDir(outputDir);
        int agentsCount =
                ReadmeUtils.countCodexAgentsFiles(agentsDir);
        Path rootDir = outputDir.getParent();
        int agentsMdCount = Files.exists(
                rootDir.resolve("AGENTS.md")) ? 1 : 0;
        int agentsOverrideCount = Files.exists(
                rootDir.resolve("AGENTS.override.md")) ? 1 : 0;
        return new Object[][]{
                {"AGENTS.md (root)", agentsMdCount},
                {"AGENTS.override.md (root)",
                        agentsOverrideCount},
                {"Codex (.codex)", codexCount},
                {"Skills (.agents)", agentsCount},
        };
    }

    private static Object[][] concatRows(
            Object[][]... groups) {
        int total = 0;
        for (Object[][] g : groups) {
            total += g.length;
        }
        Object[][] result = new Object[total][];
        int idx = 0;
        for (Object[][] g : groups) {
            System.arraycopy(g, 0, result, idx, g.length);
            idx += g.length;
        }
        return result;
    }
}
