package dev.iadev.domain.model;

import java.time.LocalDate;
import java.util.List;

/**
 * Immutable traceability report containing the
 * bidirectional requirement-to-test mapping for a
 * story or epic.
 *
 * <p>Generated by the x-test-run skill when invoked
 * with the {@code --traceability} flag. Contains all
 * data needed to render a Markdown traceability
 * matrix.</p>
 *
 * @param targetId              story or epic identifier
 * @param generatedAt           date of report generation
 * @param buildHash             git commit hash of the build
 * @param entries               rows in the traceability matrix
 * @param unmappedRequirements  requirements with no test
 * @param unmappedTests         tests with no requirement
 * @param summary               coverage summary statistics
 */
public record TraceabilityReport(
        String targetId,
        LocalDate generatedAt,
        String buildHash,
        List<TraceabilityRow> entries,
        List<String> unmappedRequirements,
        List<String> unmappedTests,
        CoverageSummary summary) {

    /**
     * Compact constructor enforcing non-null fields and
     * immutable lists.
     */
    public TraceabilityReport {
        if (targetId == null || targetId.isBlank()) {
            throw new IllegalArgumentException(
                    "targetId must not be null or blank");
        }
        if (generatedAt == null) {
            throw new IllegalArgumentException(
                    "generatedAt must not be null");
        }
        if (buildHash == null || buildHash.isBlank()) {
            throw new IllegalArgumentException(
                    "buildHash must not be null or blank");
        }
        if (summary == null) {
            throw new IllegalArgumentException(
                    "summary must not be null");
        }
        entries = List.copyOf(entries);
        unmappedRequirements =
                List.copyOf(unmappedRequirements);
        unmappedTests = List.copyOf(unmappedTests);
    }
}
