package dev.iadev.assembler;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for Consolidator — file merging and framework rule
 * consolidation.
 */
@DisplayName("Consolidator")
class ConsolidatorTest {

    @Nested
    @DisplayName("constants")
    class Constants {

        @Test
        @DisplayName("generated header is correct")
        void generatedHeader() {
            assertThat(Consolidator.GENERATED_HEADER)
                    .isEqualTo("<!-- Generated by ia-dev-env"
                            + " -- DO NOT EDIT DIRECTLY -->");
        }

        @Test
        @DisplayName("core patterns are defined")
        void corePatterns() {
            assertThat(Consolidator.CORE_PATTERNS)
                    .contains("-cdi", "-di", "-config", "-web");
        }

        @Test
        @DisplayName("data patterns are defined")
        void dataPatterns() {
            assertThat(Consolidator.DATA_PATTERNS)
                    .contains("-panache", "-jpa", "-prisma");
        }

        @Test
        @DisplayName("ops patterns are defined")
        void opsPatterns() {
            assertThat(Consolidator.OPS_PATTERNS)
                    .contains("-testing", "-observability");
        }
    }

    @Nested
    @DisplayName("consolidateFiles")
    class ConsolidateFiles {

        @Test
        @DisplayName("merges multiple files with separators")
        void mergesFiles(@TempDir Path tempDir)
                throws IOException {
            Path f1 = tempDir.resolve("a.md");
            Path f2 = tempDir.resolve("b.md");
            Files.writeString(f1, "Section A");
            Files.writeString(f2, "Section B");

            Path output = tempDir.resolve("merged.md");
            Consolidator.consolidateFiles(
                    output, List.of(f1, f2));

            String content = Files.readString(output);
            assertThat(content)
                    .startsWith(Consolidator.GENERATED_HEADER);
            assertThat(content).contains("Section A");
            assertThat(content).contains("Section B");
            assertThat(content).contains("---");
        }

        @Test
        @DisplayName("skips missing files")
        void skipsMissingFiles(@TempDir Path tempDir)
                throws IOException {
            Path existing = tempDir.resolve("exists.md");
            Files.writeString(existing, "Real content");
            Path missing = tempDir.resolve("missing.md");

            Path output = tempDir.resolve("merged.md");
            Consolidator.consolidateFiles(
                    output, List.of(existing, missing));

            String content = Files.readString(output);
            assertThat(content).contains("Real content");
        }

        @Test
        @DisplayName("does nothing for all missing files")
        void allMissing_noOutput(@TempDir Path tempDir) {
            Path output = tempDir.resolve("out.md");
            Consolidator.consolidateFiles(
                    output,
                    List.of(
                            tempDir.resolve("x.md"),
                            tempDir.resolve("y.md")));

            assertThat(output).doesNotExist();
        }

        @Test
        @DisplayName("creates parent directories")
        void createsParentDirs(@TempDir Path tempDir)
                throws IOException {
            Path src = tempDir.resolve("src.md");
            Files.writeString(src, "data");

            Path output = tempDir.resolve("a/b/out.md");
            Consolidator.consolidateFiles(
                    output, List.of(src));

            assertThat(output).exists();
        }
    }

    @Nested
    @DisplayName("consolidateFrameworkRules")
    class ConsolidateFrameworkRules {

        @Test
        @DisplayName("groups files into core, data, ops")
        void groupsIntoThreeCategories(@TempDir Path tempDir)
                throws IOException {
            Path sourceDir = tempDir.resolve("source");
            Files.createDirectories(sourceDir);
            Path rulesDir = tempDir.resolve("rules");
            Files.createDirectories(rulesDir);

            // Core file
            Files.writeString(
                    sourceDir.resolve("quarkus-cdi.md"),
                    "CDI content");
            // Data file
            Files.writeString(
                    sourceDir.resolve("quarkus-panache.md"),
                    "Panache content");
            // Ops file
            Files.writeString(
                    sourceDir.resolve("quarkus-testing.md"),
                    "Testing content");

            List<String> generated =
                    Consolidator.consolidateFrameworkRules(
                            "quarkus", rulesDir, sourceDir);

            assertThat(generated).hasSize(3);
        }

        @Test
        @DisplayName("returns empty for missing source dir")
        void missingSourceDir_returnsEmpty(
                @TempDir Path tempDir) {
            Path rulesDir = tempDir.resolve("rules");
            Path sourceDir = tempDir.resolve("nonexistent");

            List<String> result =
                    Consolidator.consolidateFrameworkRules(
                            "spring", rulesDir, sourceDir);

            assertThat(result).isEmpty();
        }

        @Test
        @DisplayName("skips empty groups")
        void skipsEmptyGroups(@TempDir Path tempDir)
                throws IOException {
            Path sourceDir = tempDir.resolve("source");
            Files.createDirectories(sourceDir);
            Path rulesDir = tempDir.resolve("rules");
            Files.createDirectories(rulesDir);

            // Only core file, no data or ops
            Files.writeString(
                    sourceDir.resolve("spring-web.md"),
                    "Web content");

            List<String> generated =
                    Consolidator.consolidateFrameworkRules(
                            "spring", rulesDir, sourceDir);

            assertThat(generated).hasSize(1);
        }
    }

    @Nested
    @DisplayName("sanitizeFilenameSegment")
    class SanitizeFilenameSegment {

        @Test
        @DisplayName("strips path separators")
        void stripsPathSeparators() {
            assertThat(Consolidator
                    .sanitizeFilenameSegment("a/b\\c"))
                    .isEqualTo("abc");
        }

        @Test
        @DisplayName("strips parent directory sequences")
        void stripsParentDir() {
            assertThat(Consolidator
                    .sanitizeFilenameSegment("../../etc"))
                    .isEqualTo("etc");
        }

        @Test
        @DisplayName("leaves safe names unchanged")
        void safeNames_unchanged() {
            assertThat(Consolidator
                    .sanitizeFilenameSegment("quarkus"))
                    .isEqualTo("quarkus");
        }
    }
}
