/**
 * CodexSkillsAssembler — generates .agents/skills/{name}/SKILL.md
 * for the OpenAI Codex CLI platform.
 *
 * Operates in 2 phases:
 * 1. Scan .claude/skills/ (already generated by SkillsAssembler)
 * 2. Copy each skill to .agents/skills/{name}/ with SKILL.md
 *    and optional references/ subdirectory
 *
 * @module
 */
import * as fs from "node:fs";
import * as path from "node:path";
import type { ProjectConfig } from "../models.js";
import type { TemplateEngine } from "../template-engine.js";
import type { AssembleResult } from "./rules-assembler.js";
import { isAccessibleDirectory } from "./codex-shared.js";

const SKILL_MD = "SKILL.md";
const REFERENCES_DIR = "references";

/** Recursively collect all file paths under a directory. */
function collectFiles(dir: string): string[] {
  const results: string[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isFile()) {
      results.push(full);
    } else if (entry.isDirectory()) {
      results.push(...collectFiles(full));
    }
  }
  return results;
}

/** Copy a skill directory (SKILL.md + references/) to destination. */
function copySkill(
  srcSkillDir: string,
  destSkillDir: string,
): string[] {
  const files: string[] = [];
  const srcSkillMd = path.join(srcSkillDir, SKILL_MD);
  if (!fs.existsSync(srcSkillMd)) return files;

  fs.mkdirSync(destSkillDir, { recursive: true });

  const destSkillMd = path.join(destSkillDir, SKILL_MD);
  fs.copyFileSync(srcSkillMd, destSkillMd);
  files.push(destSkillMd);

  const srcRefs = path.join(srcSkillDir, REFERENCES_DIR);
  if (isAccessibleDirectory(srcRefs)) {
    const destRefs = path.join(destSkillDir, REFERENCES_DIR);
    fs.cpSync(srcRefs, destRefs, { recursive: true });
    files.push(...collectFiles(destRefs));
  }

  return files;
}

/** Walk a skills directory, copying each skill subdirectory. */
function copySkillsTree(
  sourceDir: string,
  destDir: string,
): string[] {
  const files: string[] = [];
  const entries = fs.readdirSync(sourceDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name));

  for (const entry of entries) {
    const srcChild = path.join(sourceDir, entry.name);
    const destChild = path.join(destDir, entry.name);
    const srcSkillMd = path.join(srcChild, SKILL_MD);

    if (fs.existsSync(srcSkillMd)) {
      files.push(...copySkill(srcChild, destChild));
    } else if (isAccessibleDirectory(srcChild)) {
      files.push(...copySkillsTree(srcChild, destChild));
    }
  }

  return files;
}

/** Generates .agents/skills/ from already-generated .claude/skills/. */
export class CodexSkillsAssembler {
  assemble(
    _config: ProjectConfig,
    outputDir: string,
    _resourcesDir: string,
    _engine: TemplateEngine,
  ): AssembleResult {
    const warnings: string[] = [];
    const claudeSkillsDir = path.join(
      path.dirname(outputDir), ".claude", "skills",
    );

    if (!isAccessibleDirectory(claudeSkillsDir)) {
      warnings.push("No skills directory found in .claude/ output");
      return { files: [], warnings };
    }

    const destSkillsDir = path.join(outputDir, "skills");
    const files = copySkillsTree(claudeSkillsDir, destSkillsDir);

    if (files.length === 0) {
      warnings.push("No skills with SKILL.md found in .claude/skills/");
    }

    return { files, warnings };
  }
}
