/**
 * File consolidation for multi-source assembly.
 *
 * @remarks
 * Uses synchronous `node:fs` by design. Consolidation runs once per CLI
 * invocation on a bounded set of files. Sync I/O matches the Python
 * predecessor and avoids unnecessary async complexity.
 *
 * @module
 */
import * as fs from "node:fs";
import * as path from "node:path";

/** Header prepended to every consolidated output. */
export const GENERATED_HEADER =
  "<!-- Generated by ia-dev-env — DO NOT EDIT DIRECTLY -->";

/** Filename patterns for core framework extensions. */
export const CORE_PATTERNS: readonly string[] = [
  "-cdi", "-di", "-config", "-web",
  "-resteasy", "-middleware", "-resilience",
];

/** Filename patterns for data-layer extensions. */
export const DATA_PATTERNS: readonly string[] = [
  "-panache", "-jpa", "-prisma", "-sqlalchemy",
  "-exposed", "-ef", "-orm", "-database",
];

/** Filename patterns for operations extensions. */
export const OPS_PATTERNS: readonly string[] = [
  "-testing", "-observability",
  "-native-build", "-infrastructure",
];

/**
 * Merge multiple source files into a single output.
 *
 * Adds a generated header and `---` separators between sections.
 * Creates parent directories if needed. Skips missing files.
 */
export function consolidateFiles(
  outputPath: string,
  sourcePaths: readonly string[],
): void {
  const existing = sourcePaths.filter(
    (p) => fs.existsSync(p) && fs.statSync(p).isFile(),
  );

  if (existing.length === 0) return;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  const lines: string[] = [GENERATED_HEADER, ""];
  for (const src of existing) {
    lines.push("", "---", "", fs.readFileSync(src, "utf-8"), "");
  }
  fs.writeFileSync(outputPath, lines.join("\n"));
}

/**
 * Group framework files into 3 consolidated outputs (core, data, ops).
 *
 * @returns List of generated file paths (only for non-empty groups).
 */
export function consolidateFrameworkRules(
  framework: string,
  rulesDir: string,
  sourceDir: string,
): string[] {
  if (
    !fs.existsSync(sourceDir) ||
    !fs.statSync(sourceDir).isDirectory()
  ) {
    return [];
  }

  const safeFramework = sanitizeFilenameSegment(framework);
  const allFiles = fs
    .readdirSync(sourceDir)
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => path.join(sourceDir, f));

  const groups = classifyFrameworkFiles(allFiles);
  const generated: string[] = [];

  for (const { prefix, label, files } of groups) {
    if (files.length === 0) continue;
    const out = path.join(rulesDir, `${prefix}-${safeFramework}-${label}.md`);
    consolidateFiles(out, files);
    generated.push(out);
  }

  return generated;
}

interface FileGroup {
  readonly prefix: string;
  readonly label: string;
  readonly files: string[];
}

function classifyFrameworkFiles(
  allFiles: readonly string[],
): FileGroup[] {
  const core: string[] = [];
  const data: string[] = [];
  const ops: string[] = [];

  for (const filePath of allFiles) {
    const name = path.basename(filePath);
    if (matchesAny(name, CORE_PATTERNS)) {
      core.push(filePath);
    } else if (matchesAny(name, DATA_PATTERNS)) {
      data.push(filePath);
    } else if (matchesAny(name, OPS_PATTERNS)) {
      ops.push(filePath);
    }
  }

  return [
    { prefix: "30", label: "core", files: core },
    { prefix: "31", label: "data", files: data },
    { prefix: "32", label: "operations", files: ops },
  ];
}

function matchesAny(
  filename: string,
  patterns: readonly string[],
): boolean {
  return patterns.some((pattern) => filename.includes(pattern));
}

/**
 * Strip path separators and parent-directory sequences from a filename segment.
 *
 * Prevents path traversal when user-supplied values (e.g. framework name)
 * are interpolated into output filenames.
 */
export function sanitizeFilenameSegment(segment: string): string {
  return segment.replace(/[/\\]/g, "").replace(/\.\./g, "");
}
