/**
 * ReadmeAssembler -- generates README.md from template or minimal fallback.
 *
 * Migrated from Python `assembler/readme_assembler.py` (431 lines).
 * Scans files generated by all preceding assemblers to produce a
 * comprehensive README.md with dynamic counts, mapping tables,
 * knowledge pack detection, hooks/settings documentation, and
 * a generation summary.
 *
 * @module
 */
import * as fs from "node:fs";
import * as path from "node:path";
import type { ProjectConfig } from "../models.js";
import type { TemplateEngine } from "../template-engine.js";
import {
  buildRulesTable, buildSkillsTable, buildAgentsTable,
  buildKnowledgePacksTable, buildReadmeHooksSection,
  buildSettingsSection, buildMappingTable, buildGenerationSummary,
} from "./readme-tables.js";

// Re-export table builders so consumers can import from one module
export {
  buildRulesTable, buildSkillsTable, buildAgentsTable,
  buildKnowledgePacksTable, buildReadmeHooksSection,
  buildSettingsSection, buildMappingTable, buildGenerationSummary,
} from "./readme-tables.js";

/** Count `.md` files in `outputDir/rules/`. Returns 0 if dir missing. */
export function countRules(outputDir: string): number {
  const rulesDir = path.join(outputDir, "rules");
  if (!fs.existsSync(rulesDir)) return 0;
  return fs.readdirSync(rulesDir)
    .filter((f) => f.endsWith(".md")).length;
}

/** Count `SKILL.md` files in `outputDir/skills/` subdirs. */
export function countSkills(outputDir: string): number {
  const skillsDir = path.join(outputDir, "skills");
  if (!fs.existsSync(skillsDir)) return 0;
  return fs.readdirSync(skillsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .filter((d) => fs.existsSync(
      path.join(skillsDir, d.name, "SKILL.md"),
    )).length;
}

/** Count `.md` files in `outputDir/agents/`. */
export function countAgents(outputDir: string): number {
  const agentsDir = path.join(outputDir, "agents");
  if (!fs.existsSync(agentsDir)) return 0;
  return fs.readdirSync(agentsDir)
    .filter((f) => f.endsWith(".md")).length;
}

/** Count skills where `isKnowledgePack()` returns true. */
export function countKnowledgePacks(outputDir: string): number {
  const skillsDir = path.join(outputDir, "skills");
  if (!fs.existsSync(skillsDir)) return 0;
  return fs.readdirSync(skillsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .filter((d) => {
      const p = path.join(skillsDir, d.name, "SKILL.md");
      return fs.existsSync(p) && isKnowledgePack(p);
    }).length;
}

/** Count all entries in `outputDir/hooks/`. */
export function countHooks(outputDir: string): number {
  const hooksDir = path.join(outputDir, "hooks");
  if (!fs.existsSync(hooksDir)) return 0;
  return fs.readdirSync(hooksDir).length;
}

/** Count `settings.json` and `settings.local.json`. */
export function countSettings(outputDir: string): number {
  let count = 0;
  if (fs.existsSync(path.join(outputDir, "settings.json"))) {
    count += 1;
  }
  if (fs.existsSync(path.join(outputDir, "settings.local.json"))) {
    count += 1;
  }
  return count;
}

/** Recursively count all files under `githubDir`. */
export function countGithubFiles(githubDir: string): number {
  if (!fs.existsSync(githubDir)) return 0;
  return fs.readdirSync(githubDir, {
    withFileTypes: true, recursive: true,
  }).filter((e) => e.isFile()).length;
}

/** Count files directly under `githubDir/{component}/`. */
export function countGithubComponent(
  githubDir: string, component: string,
): number {
  const compDir = path.join(githubDir, component);
  if (!fs.existsSync(compDir)) return 0;
  return fs.readdirSync(compDir, { withFileTypes: true })
    .filter((e) => e.isFile()).length;
}

/** Count `SKILL.md` in `githubDir/skills/` subdirs. */
export function countGithubSkills(githubDir: string): number {
  const skillsDir = path.join(githubDir, "skills");
  if (!fs.existsSync(skillsDir)) return 0;
  return fs.readdirSync(skillsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .filter((d) => fs.existsSync(
      path.join(skillsDir, d.name, "SKILL.md"),
    )).length;
}

/** Return true if SKILL.md content flags a knowledge pack. */
export function isKnowledgePack(skillMdPath: string): boolean {
  const text = fs.readFileSync(skillMdPath, "utf-8");
  if (text.includes("user-invocable: false")) return true;
  for (const line of text.split("\n")) {
    if (line.startsWith("# Knowledge Pack")) return true;
  }
  return false;
}

/** Extract leading digits from a rule filename. */
export function extractRuleNumber(filename: string): string {
  const match = filename.match(/^(\d+)/);
  return match?.[1] ?? "";
}

/** Strip leading number+hyphen and `.md`, replace hyphens with spaces. */
export function extractRuleScope(filename: string): string {
  let name = filename.replace(/^\d+-/, "");
  name = name.replace(/\.md$/, "");
  return name.replace(/-/g, " ");
}

/** Read SKILL.md and extract `description:` value. */
export function extractSkillDescription(
  skillMdPath: string,
): string {
  const text = fs.readFileSync(skillMdPath, "utf-8");
  for (const line of text.split("\n")) {
    if (line.startsWith("description:")) {
      const desc = (line.split(":", 2)[1] ?? "").trim();
      return desc.replace(/^["']|["']$/g, "");
    }
  }
  return "";
}

/** Build full README from template with `{{PLACEHOLDER}}` tokens. */
export function generateReadme(
  config: ProjectConfig,
  outputDir: string,
  templatePath: string,
): string {
  let content = fs.readFileSync(templatePath, "utf-8");
  content = content.replace("{{PROJECT_NAME}}", config.project.name);
  content = content.replace("{{RULES_COUNT}}", String(countRules(outputDir)));
  content = content.replace("{{SKILLS_COUNT}}", String(countSkills(outputDir)));
  content = content.replace("{{AGENTS_COUNT}}", String(countAgents(outputDir)));
  content = content.replace("{{RULES_TABLE}}", buildRulesTable(outputDir));
  content = content.replace("{{SKILLS_TABLE}}", buildSkillsTable(outputDir));
  content = content.replace("{{AGENTS_TABLE}}", buildAgentsTable(outputDir));
  content = content.replace("{{HOOKS_SECTION}}", buildReadmeHooksSection(config));
  content = content.replace("{{KNOWLEDGE_PACKS_TABLE}}", buildKnowledgePacksTable(outputDir));
  content = content.replace("{{SETTINGS_SECTION}}", buildSettingsSection());
  content = content.replace("{{MAPPING_TABLE}}", buildMappingTable(outputDir));
  content = content.replace("{{GENERATION_SUMMARY}}", buildGenerationSummary(outputDir, config));
  return content;
}

/** Generate minimal README with basic project info. */
export function generateMinimalReadme(
  config: ProjectConfig,
): string {
  const ifaces = config.interfaces
    .map((i) => i.type).join(" ") || "none";
  const header =
    `# .claude/ \u2014 ${config.project.name}\n`
    + "\n"
    + "This directory contains the Claude Code configuration"
    + ` for **${config.project.name}**.\n`
    + "\n";
  const structure = buildStructureBlock();
  const tips = buildTipsBlock(config.architecture.style, ifaces);
  return header + structure + tips;
}

/** Build the directory structure section for minimal README. */
export function buildStructureBlock(): string {
  return (
    "## Structure\n\n```\n"
    + ".claude/\n"
    + "\u251c\u2500\u2500 README.md               \u2190 You are here\n"
    + "\u251c\u2500\u2500 settings.json           \u2190 Shared config (committed to git)\n"
    + "\u251c\u2500\u2500 settings.local.json     \u2190 Local overrides (gitignored)\n"
    + "\u251c\u2500\u2500 rules/                  \u2190 Coding rules (loaded in system prompt)\n"
    + "\u2502   \u251c\u2500\u2500 patterns/           \u2190 Design patterns (architecture-driven)\n"
    + "\u2502   \u2514\u2500\u2500 protocols/          \u2190 Protocol conventions (interface-driven)\n"
    + "\u251c\u2500\u2500 skills/                 \u2190 Skills invocable via /command\n"
    + "\u251c\u2500\u2500 agents/                 \u2190 AI personas (used by skills)\n"
    + "\u2514\u2500\u2500 hooks/                  \u2190 Automation (post-compile, etc.)\n"
    + "```\n\n"
  );
}

/** Build the tips section for minimal README. */
export function buildTipsBlock(
  archStyle: string, ifaces: string,
): string {
  return (
    "## Tips\n\n"
    + "- **Rules are always active** \u2014 loaded automatically in every conversation\n"
    + `- **Patterns are selected** \u2014 based on architecture style (${archStyle})\n`
    + `- **Protocols are selected** \u2014 based on interfaces (${ifaces})\n`
    + "- **Skills are lazy** \u2014 only load when you type `/name`\n"
    + "- **Agents are not invoked directly** \u2014 used by skills internally\n"
    + "- **Hooks run automatically** \u2014 compile check after editing source files\n"
  );
}

/**
 * Generates README.md from template or minimal fallback.
 *
 * The `engine` parameter is accepted for API uniformity with other
 * assemblers but is not used; README uses `{{DOUBLE_BRACE}}` tokens
 * replaced via `String.replace()`, not the TemplateEngine.
 */
export class ReadmeAssembler {
  /** Generate README.md in outputDir. */
  assemble(
    config: ProjectConfig,
    outputDir: string,
    resourcesDir: string,
    _engine: TemplateEngine,
  ): string[] {
    const templatePath = path.join(
      resourcesDir, "readme-template.md",
    );
    const content = fs.existsSync(templatePath)
      ? generateReadme(config, outputDir, templatePath)
      : generateMinimalReadme(config);
    const dest = path.join(outputDir, "README.md");
    fs.writeFileSync(dest, content, "utf-8");
    return [dest];
  }
}
