package dev.iadev.application.assembler;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for SummaryTableBuilder — builds generation summary
 * table and settings section for README.md.
 */
@DisplayName("SummaryTableBuilder")
class SummaryTableBuilderTest {

    private final SummaryTableBuilder builder =
            new SummaryTableBuilder();

    @Nested
    @DisplayName("buildGenerationSummary")
    class BuildGenerationSummary {

        @Test
        @DisplayName("contains 11 component rows")
        void build_whenCalled_containsElevenComponents(
                @TempDir Path tempDir) throws IOException {
            Path claudeDir = setupMinimalOutput(tempDir);

            String summary =
                    builder.buildGenerationSummary(
                            claudeDir);

            assertThat(summary)
                    .contains("| Component | Count |")
                    .contains("|-----------|-------|");
            int dataRows = 0;
            for (String line : summary.split("\n")) {
                if (line.startsWith("| ")
                        && !line.startsWith("| Component")
                        && !line.startsWith("|---")) {
                    dataRows++;
                }
            }
            assertThat(dataRows).isEqualTo(11);
        }

        @Test
        @DisplayName("contains ia-dev-env version")
        void build_whenCalled_containsVersion(
                @TempDir Path tempDir) throws IOException {
            Path claudeDir = setupMinimalOutput(tempDir);

            String summary =
                    builder.buildGenerationSummary(
                            claudeDir);

            assertThat(summary)
                    .contains("Generated by `ia-dev-env"
                            + " v0.1.0`.");
        }

        @Test
        @DisplayName("includes all component labels")
        void build_whenCalled_includesAllLabels(
                @TempDir Path tempDir) throws IOException {
            Path claudeDir = setupMinimalOutput(tempDir);

            String summary =
                    builder.buildGenerationSummary(
                            claudeDir);

            assertThat(summary)
                    .contains("Rules (.claude)")
                    .contains("Skills (.claude)")
                    .contains("Knowledge Packs (.claude)")
                    .contains("Agents (.claude)")
                    .contains("Hooks (.claude)")
                    .contains("Settings (.claude)")
                    .contains("Plan Templates (.claude)")
                    .contains("AGENTS.md (root)")
                    .contains("AGENTS.override.md (root)")
                    .contains("Codex (.codex)")
                    .contains("Skills (.agents)");
        }

        @Test
        @DisplayName("counts plan templates when present")
        void build_withTemplates_countsPlanTemplates(
                @TempDir Path tempDir) throws IOException {
            Path claudeDir = setupMinimalOutput(tempDir);
            Path claudeTemplates =
                    Files.createDirectories(
                            claudeDir.resolve("templates"));
            for (int i = 1; i <= 12; i++) {
                Files.writeString(
                        claudeTemplates.resolve(
                                "_TEMPLATE-PLAN-" + i
                                        + ".md"),
                        "content",
                        StandardCharsets.UTF_8);
            }

            String summary =
                    builder.buildGenerationSummary(
                            claudeDir);

            assertThat(summary)
                    .contains("Plan Templates (.claude)"
                            + " | 12 |");
        }

        @Test
        @DisplayName("summary with codex and agents")
        void build_withAllExtras_summary(
                @TempDir Path tempDir) throws IOException {
            Path claudeDir = Files.createDirectories(
                    tempDir.resolve(".claude"));
            Files.createDirectories(
                    tempDir.resolve(".github"));
            Path codexDir = Files.createDirectories(
                    tempDir.resolve(".codex"));
            Files.writeString(
                    codexDir.resolve("config.toml"),
                    "c", StandardCharsets.UTF_8);
            Path agentsDir = Files.createDirectories(
                    tempDir.resolve(".agents"));
            Files.writeString(
                    agentsDir.resolve("AGENTS.md"),
                    "c", StandardCharsets.UTF_8);
            Files.writeString(
                    tempDir.resolve("AGENTS.md"),
                    "c", StandardCharsets.UTF_8);
            Files.writeString(
                    tempDir.resolve("AGENTS.override.md"),
                    "c", StandardCharsets.UTF_8);

            String summary =
                    builder.buildGenerationSummary(
                            claudeDir);

            assertThat(summary)
                    .contains("Codex (.codex)")
                    .contains("Skills (.agents)")
                    .contains("AGENTS.md (root)")
                    .contains("AGENTS.override.md (root)");
        }

        private Path setupMinimalOutput(Path tempDir)
                throws IOException {
            return Files.createDirectories(
                    tempDir.resolve(".claude"));
        }
    }

    @Nested
    @DisplayName("buildSettingsSection")
    class BuildSettingsSection {

        @Test
        @DisplayName("contains settings.json description")
        void build_whenCalled_containsSettingsJsonDesc() {
            String section =
                    builder.buildSettingsSection();

            assertThat(section)
                    .contains("### settings.json")
                    .contains("permissions.allow")
                    .contains("### settings.local.json")
                    .contains("Local overrides");
        }
    }
}
