package dev.iadev.application.assembler;

import dev.iadev.domain.model.Platform;
import dev.iadev.domain.model.ProjectFoundation;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * Builds the generation summary table and settings section
 * for README.md.
 *
 * <p>Generates component counts for all artifact types
 * under the .claude/ directory. Also provides the static
 * settings documentation section.</p>
 *
 * @see ReadmeTables
 * @see ReadmeUtils
 */
public final class SummaryTableBuilder {

    SummaryTableBuilder() {
        // package-private constructor
    }

    /**
     * Builds the generation summary table with component
     * counts (all platforms).
     *
     * @param outputDir the .claude/ output directory
     * @return formatted generation summary
     */
    String buildGenerationSummary(Path outputDir) {
        return buildGenerationSummary(outputDir, Set.of());
    }

    /**
     * Builds a platform-filtered generation summary table.
     *
     * <p>When platforms is empty or contains all
     * user-selectable platforms, all rows are shown.
     * Otherwise, only rows matching the requested
     * platform(s) are included.</p>
     *
     * @param outputDir the .claude/ output directory
     * @param platforms the active platforms (empty = all)
     * @return formatted generation summary
     */
    String buildGenerationSummary(
            Path outputDir, Set<Platform> platforms) {
        Object[][] allRows = buildSummaryRows(outputDir);
        Object[][] rows = SummaryRowFilter.filter(
                allRows, platforms);
        List<String> lines = new ArrayList<>();
        lines.add("| Component | Count |");
        lines.add("|-----------|-------|");
        for (Object[] row : rows) {
            lines.add("| %s | %s |"
                    .formatted(row[0], row[1]));
        }
        lines.add("");
        String ver = ProjectFoundation.DEFAULT.version();
        lines.add("Generated by `ia-dev-env v%s`."
                .formatted(ver));
        return String.join("\n", lines);
    }

    /**
     * Builds static settings section content.
     *
     * @return formatted settings section
     */
    String buildSettingsSection() {
        return "### settings.json\n"
                + "\n"
                + "Permissions are configured in"
                + " `settings.json`"
                + " under `permissions.allow`.\n"
                + "This controls which Bash commands"
                + " Claude Code"
                + " can run without asking.\n"
                + "\n"
                + "### settings.local.json\n"
                + "\n"
                + "Local overrides (gitignored)."
                + " Use for personal"
                + " preferences or team-specific tools.\n"
                + "\n"
                + "See the files directly for current"
                + " configuration.";
    }

    private static Object[][] buildSummaryRows(
            Path outputDir) {
        return buildClaudeRows(outputDir);
    }

    private static Object[][] buildClaudeRows(
            Path outputDir) {
        int kps = ReadmeUtils
                .countKnowledgePacks(outputDir);
        return new Object[][]{
                {"Rules (.claude)",
                        ReadmeUtils.countRules(outputDir)},
                {"Skills (.claude)",
                        ReadmeUtils.countSkills(outputDir)
                                - kps},
                {"Knowledge Packs (.claude)", kps},
                {"Agents (.claude)",
                        ReadmeUtils.countAgents(outputDir)},
                {"Hooks (.claude)",
                        ReadmeUtils.countHooks(outputDir)},
                {"Settings (.claude)",
                        ReadmeUtils.countSettings(outputDir)},
                {"Plan Templates (.claude)",
                        countPlanTemplates(outputDir,
                                "templates")},
        };
    }

    private static int countPlanTemplates(
            Path baseDir, String subdir) {
        Path templatesDir = baseDir.resolve(subdir);
        if (!Files.isDirectory(templatesDir)) {
            return 0;
        }
        try (var stream = Files.list(templatesDir)) {
            return (int) stream
                    .filter(p -> p.getFileName()
                            .toString()
                            .startsWith("_TEMPLATE-"))
                    .filter(p -> p.getFileName()
                            .toString()
                            .endsWith(".md"))
                    .count();
        } catch (IOException e) {
            return 0;
        }
    }

}
