from __future__ import annotations

from pathlib import Path
from typing import Dict, List

CORE_PATTERNS = (
    "-cdi", "-di-", "-config", "-web", "-resteasy",
    "-middleware", "-resilience",
)
DATA_PATTERNS = (
    "-panache", "-jpa", "-prisma", "-sqlalchemy",
    "-exposed", "-ef-", "-orm", "-database",
)
OPS_PATTERNS = (
    "-testing", "-observability", "-native-build",
    "-infrastructure",
)


def consolidate_files(
    output_path: Path,
    source_paths: List[Path],
) -> None:
    """Merge multiple source files into a single output with separators."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["<!-- Generated by claude-setup — DO NOT EDIT DIRECTLY -->", ""]
    first = True
    for src in source_paths:
        if not src.is_file():
            continue
        if not first:
            lines.extend(["", "---", ""])
        lines.append(src.read_text(encoding="utf-8").rstrip())
        lines.append("")
        first = False
    output_path.write_text("\n".join(lines), encoding="utf-8")


def consolidate_framework_rules(
    framework: str,
    rules_dir: Path,
    source_dir: Path,
) -> List[Path]:
    """Group framework files into 3 consolidated outputs."""
    if not source_dir.is_dir():
        return []
    groups = _classify_framework_files(source_dir)
    generated: List[Path] = []
    for suffix, files in [
        ("core", groups.get("core", [])),
        ("data", groups.get("data", [])),
        ("operations", groups.get("operations", [])),
    ]:
        if not files:
            continue
        num = {"core": "30", "data": "31", "operations": "32"}[suffix]
        out = rules_dir / f"{num}-{framework}-{suffix}.md"
        consolidate_files(out, files)
        generated.append(out)
    return generated


def _classify_framework_files(
    source_dir: Path,
) -> Dict[str, List[Path]]:
    groups: Dict[str, List[Path]] = {
        "core": [], "data": [], "operations": [],
    }
    for md_file in sorted(source_dir.glob("*.md")):
        name = md_file.name.lower()
        group = _match_group(name)
        if group:
            groups[group].append(md_file)
    return groups


def _match_group(filename: str) -> str:
    for pattern in CORE_PATTERNS:
        if pattern in filename:
            return "core"
    for pattern in DATA_PATTERNS:
        if pattern in filename:
            return "data"
    for pattern in OPS_PATTERNS:
        if pattern in filename:
            return "operations"
    return ""
