from __future__ import annotations

from pathlib import Path
from typing import List

GENERATED_HEADER = "<!-- Generated by claude-setup — DO NOT EDIT DIRECTLY -->"

CORE_PATTERNS: List[str] = [
    "-cdi", "-di", "-config", "-web",
    "-resteasy", "-middleware", "-resilience",
]
DATA_PATTERNS: List[str] = [
    "-panache", "-jpa", "-prisma", "-sqlalchemy",
    "-exposed", "-ef", "-orm", "-database",
]
OPS_PATTERNS: List[str] = [
    "-testing", "-observability",
    "-native-build", "-infrastructure",
]


def consolidate_files(
    output_path: Path,
    source_paths: List[Path],
) -> None:
    """Merge multiple source files into a single output.

    Adds a generated header and '---' separators between sections.
    Creates parent directories if needed. Skips missing files.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    existing = [p for p in source_paths if p.is_file()]
    if not existing:
        return
    lines = [GENERATED_HEADER, ""]
    for src in existing:
        lines.extend(["", "---", "", src.read_text(), ""])
    output_path.write_text("\n".join(lines))


def consolidate_framework_rules(
    framework: str,
    rules_dir: Path,
    source_dir: Path,
) -> List[Path]:
    """Group framework files into 3 consolidated outputs.

    Returns list of generated file paths (only for non-empty groups).
    """
    if not source_dir.is_dir():
        return []
    all_files = sorted(source_dir.glob("*.md"))
    generated: List[Path] = []
    groups = _classify_framework_files(all_files)
    for prefix, label, files in groups:
        if not files:
            continue
        out = rules_dir / f"{prefix}-{framework}-{label}.md"
        consolidate_files(out, files)
        generated.append(out)
    return generated


def _classify_framework_files(
    all_files: List[Path],
) -> List[tuple]:
    """Classify files into core/data/ops groups."""
    core: List[Path] = []
    data: List[Path] = []
    ops: List[Path] = []
    for f in all_files:
        name = f.name
        if _matches_any(name, CORE_PATTERNS):
            core.append(f)
        elif _matches_any(name, DATA_PATTERNS):
            data.append(f)
        elif _matches_any(name, OPS_PATTERNS):
            ops.append(f)
    return [("30", "core", core), ("31", "data", data), ("32", "operations", ops)]


def _matches_any(filename: str, patterns: List[str]) -> bool:
    """Check if filename contains any of the given patterns."""
    return any(pattern in filename for pattern in patterns)
